version: '3'
services:
  app-mysql:
    container_name: app-mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: emp_db
      MYSQL_ROOT_PASSWORD: welcome
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"

  app:
    build:
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    command: mvn clean spring-boot:run
    depends_on:
    - app-mysql